FROM python:3.11.4-slim

RUN apt update

WORKDIR /app

RUN useradd appuser && chown appuser ./

RUN pip install --upgrade pip && \
    pip install poetry && \
    poetry config virtualenvs.create false --local

COPY --chown=appuser poetry.lock pyproject.toml ./

RUN poetry install --no-root

COPY --chown=appuser . ./