AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: aws

Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  CalculateDateOfBirthSQS:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: "UserDataDestination"

  CalculateDateOfBirthSNS:
    Type: "AWS::SNS::Topic"

  CalculateDateOfBirthFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      CodeUri: apps/
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref CalculateDateOfBirthSNS
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt CalculateDateOfBirthSNS.TopicName
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        CalculateDateOfBirthEvent:
          Type: SQS
          Properties:
            Queue:
              Fn::GetAtt:
                - CalculateDateOfBirthSQS
                - Arn
      Timeout: 10

Outputs:
  MyLambdaFunctionArn:
    Description: Lambda Function ARN
    Value: !GetAtt CalculateDateOfBirthFunction.Arn

  CalculateDateOfBirthSNSArn:
    Description: SNS Topic ARN
    Value: !Ref CalculateDateOfBirthSNS
