# Generated by Django 4.2.6 on 2023-10-30 18:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('body', models.JSONField()),
                ('status', models.IntegerField(choices=[(-1, 'Failed'), (1, 'Schedule'), (2, 'Succeeded')], default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
