# Generated by Django 4.2.6 on 2023-10-29 15:11

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserData",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name of User")),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail of user")),
                ("age", models.PositiveIntegerField(verbose_name="Age of User")),
                (
                    "year_of_birthday",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Year of birthday of User"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
